
--TABLES
-------------------------------------------------------------------------------
CREATE TABLE USER(
USER_ID NUMBER PRIMARY KEY, 
USERNAME VARCHAR(20)UNIQUE NOT NULL, 
PASSWORD VARCHAR(20) UNIQUE,
FIRST_NAME VARCHAR(20), 
LAST_NAME VARCHAR(20), 
EMAIL VARCHAR(20),
SUPER_USER NUMBER
)

CREATE TABLE REIMBURSE(
REIMBURSE_ID NUMBER PRIMARY KEY,
USER_ID NUMBER FOREIGN REFERENCES USER(USER_ID),
PENDING_STATE NUMBER, --0 FOR UNREVIEWING, 1 FOR REJECTED, 2 FOR RESOLVED
MANAGER_VIEW VARCHAR(20), --IF 1 OR 2, LOOK WHO CHANGED IT
IMAGE_REF VARCHAR(100)
)




--SEQUENCES AND TRIGGERS FOR PRIMARY KEYS
-------------------------------------------------------------------------------
CREATE SEQUENCE SQ_UNIQUE_USER_ID
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_UNIQUE_REIMBURSE_ID
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_BEFORE_INSERT_USER
BEFORE INSERT ON USER
FOR EACH ROW
BEGIN
    SELECT SQ_UNIQUE_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_BEFORE_INSERT_REIMBURSE
BEFORE INSERT ON REIMBURSE
FOR EACH ROW
BEGIN
    SELECT SQ_UNIQUE_REIMBURSE_ID.NEXTVAL INTO :NEW.REIMBURSE_ID FROM DUAL;
END;

--
-------------------------------------------------------------------------------