CREATE TABLE EMPLOYEE (EMPLOYEE_ID INT, EMP_FIRSTNAME VARCHAR(100), EMP_LASTNAME VARCHAR(100), DEPARTMENT_ID INT, SALARY NUMBER, EMP_EMAIL VARCHAR(100));

CREATE TABLE DEPARTMENT (DEPARTMENT_ID INT, DEPARTMENT_NAME VARCHAR(100));

CREATE SEQUENCE SQ_UNIQUE_EMPLOYEE_ID
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_UNIQUE_DEPARTMENT_ID
START WITH 1
INCREMENT BY 1;



CREATE OR REPLACE TRIGGER TR_BEFORE_INSERT_CUSTOMER
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_UNIQUE_EMPLOYEE_ID.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;

END;

CREATE OR REPLACE TRIGGER TR_BEFORE_INSERT_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_UNIQUE_DEPARTMENT_ID.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;

END;

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Jason', 'McCob', 30000, 'jason.mccob@employee.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Eric', 'McCob', 60000, 'eric.mccob@employee.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Lucy', 'Anders', 40000, 'lucy.anders@employee.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Greg', 'Stevenson', 50000, 'greg.stevenson@employee.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Rob', 'Mclain', 35000, 'rob.mclain@employee.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME , EMP_LASTNAME , SALARY, EMP_EMAIL)
VALUES ('Ana', 'Nastile', 55000, 'ana.nas@employee.com');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES ('HR MANAGEMENT');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES ('PRODUCTIONS');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES ('FINANCE');



CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE (DEPARTID NUMBER, RAISE NUMBER)
IS
TEMPSALARY NUMBER;
NEWSALARY NUMBER;
EMPLOYEEID NUMBER;
BEGIN
    OPEN S FOR
    SELECT SALARY, EMPLOYEE_ID INTO TEMPSALARY, EMPLOYEEID
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = DEPARTID;
    NEWSALARY := TEMPSALARY * RAISE;
    
    UPDATE EMPLOYEE
    SET SALARY = NEWSALARY 
    WHERE EMPLOYEE_ID = EMPLOYEEID;
    
END;
